projects:
  myapi:
    schemaPath: src/graphql/schema.json
    includes:
      - index
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
